apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-deployment
  labels:
    app: auto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto
  template:
    metadata:
      labels:
        app: auto
    spec:
      containers:
      - name: auto
        image: 533267333644.dkr.ecr.us-east-1.amazonaws.com/shopping-site-auto:5cb37c28c6a966d8f42d9f50954b75e511cfe1dc
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: auto-service
  labels:
    app: auto
spec:
  type: ClusterIP
  selector:
    app: auto
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
