apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 533267333644.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlegrocery:985c8170d83e76f443db9ef235392a3b0644c8a9
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: googlegrocery-service
  labels:
    app: googlegrocery
spec:
  type: ClusterIP
  selector:
    app: googlegrocery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
